[project]
name = "codex-4x-game"
version = "0.1.0"
requires-python = ">=3.11"

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "I", "B"]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]
