[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I"]
ignore = []

[project]
name = "codex-4x-game"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pygame>=2.6.0",
    "pygame_gui>=0.6.9",
]
